### ISSUE TITLE
Bot is spamming `Gateway: Error handling Dispatch (TYPING_START)`

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/eevee-sleep-discord-bot#11]
Reason unknown. Could relate to https://github.com/discord-net/Discord.Net/issues/1870.

Maybe check after #7 and #8 are completed.

```
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37: [2023-11-08 05:23:37] fail: Eevee.Sleep.Bot.Handlers.OnLogHandler[0]
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:       Gateway: Error handling Dispatch (TYPING_START)
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:       System.NullReferenceException: Object reference not set to an instance of an object.
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:          at System.Collections.Immutable.ImmutableArray`1.get_Length()
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:          at Discord.WebSocket.SocketGuildChannel.GetPermissionOverwrite(IRole role)
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:          at Discord.WebSocket.SocketThreadChannel.GetPermissionOverwrite(IRole role)
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:          at Discord.Permissions.ResolveChannel(IGuild guild, IGuildUser user, IGuildChannel channel, UInt64 guildPermissions)
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:          at Discord.WebSocket.SocketTextChannel.GetUser(UInt64 id)
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:          at Discord.WebSocket.SocketGuildChannel.GetUserInternal(UInt64 id)
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:          at Discord.WebSocket.SocketChannel.GetUser(UInt64 id)
16|Eevee.Sleep.Bot  | 2023-11-08T05:23:37:          at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
```

**Comment by RaenonX** [comment]
Looks like a bug introduced in `Discord.Net` v3.12. Will just skip the version.
